-- ============================================================
-- TechMall 用户服务数据库
-- ============================================================
CREATE DATABASE IF NOT EXISTS techmall_user
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE techmall_user;

DROP TABLE IF EXISTS t_user;
CREATE TABLE t_user (
    id          BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
    username    VARCHAR(50)  NOT NULL COMMENT '用户名',
    password    VARCHAR(255) NOT NULL COMMENT '密码(BCrypt)',
    nickname    VARCHAR(50)  DEFAULT NULL COMMENT '昵称',
    phone       VARCHAR(20)  DEFAULT NULL COMMENT '手机号',
    email       VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
    role        VARCHAR(20)  NOT NULL DEFAULT 'USER' COMMENT 'USER/MERCHANT/ADMIN',
    status      TINYINT      NOT NULL DEFAULT 1 COMMENT '0-禁用, 1-正常',
    created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_username (username),
    KEY idx_role (role),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

-- 初始数据: 密码均为 123456 (BCrypt)
-- BCrypt hash generated by: Python bcrypt, cost=12
INSERT INTO t_user (username, password, nickname, phone, email, role) VALUES
('admin',     '$2b$12$uiKglOFQgMDr5OIbZpf3gud/CwNxc9FiII8VGfXK.c/QZ868NNZW2', '系统管理员', '13800000001', 'admin@techmall.com',     'ADMIN'),
('merchant1', '$2b$12$uiKglOFQgMDr5OIbZpf3gud/CwNxc9FiII8VGfXK.c/QZ868NNZW2', '数码旗舰店', '13800000002', 'merchant1@techmall.com', 'MERCHANT'),
('merchant2', '$2b$12$uiKglOFQgMDr5OIbZpf3gud/CwNxc9FiII8VGfXK.c/QZ868NNZW2', '耳机专营店', '13800000003', 'merchant2@techmall.com', 'MERCHANT'),
('user1',     '$2b$12$uiKglOFQgMDr5OIbZpf3gud/CwNxc9FiII8VGfXK.c/QZ868NNZW2', '测试用户',   '13800000004', 'user1@techmall.com',     'USER');
