server:
  port: 8081

spring:
  config:
    import: nacos:${spring.application.name}.yml
  application:
    name: techmall-user-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
