server:
  port: 8082

spring:
  config:
    import: nacos:${spring.application.name}.yml
  application:
    name: techmall-product-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
  servlet:
    multipart:
      max-file-size: 10MB


