server:
  port: 8083

spring:
  config:
    import: nacos:${spring.application.name}.yml
  application:
    name: techmall-order-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
    sentinel:
      transport:
        dashboard: localhost:8858


